# Generated by Django 4.2.5 on 2023-09-20 08:56

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, null=True, upload_to='brand_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to='category_img/')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='apis.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InHouseProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('product_type', models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical')], max_length=200)),
                ('sku', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('psc', 'psc'), ('kg', 'kg'), ('ltrs', 'ltrs'), ('gms', 'gms')], max_length=100)),
                ('color', models.CharField(max_length=150)),
                ('unit_price', models.FloatField()),
                ('purchase_price', models.FloatField()),
                ('tax', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('discount_type', models.CharField(blank=True, choices=[('flat', 'Flat'), ('percent', 'Percent')], max_length=200, null=True)),
                ('total_quantity', models.PositiveIntegerField()),
                ('minimum_order_quantity', models.PositiveBigIntegerField()),
                ('shipping_cost', models.FloatField(blank=True, null=True)),
                ('meta_title', models.TextField()),
                ('meta_description', models.TextField()),
                ('meta_image', models.FileField(blank=True, null=True, upload_to='meta_image/')),
                ('product_images', models.FileField(blank=True, null=True, upload_to='products_img')),
                ('product_thumbnail', models.FileField(blank=True, null=True, upload_to='product_thumbnail/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.category')),
            ],
        ),
    ]
